---
- rule:
    type: checkbox
    keywords:
      - "Removing API(s)"
      - "Updating API in stable version"
    onCheckedLabels:
      - breakingChange
    onCheckedComments: "Hi, @${PRAuthor} your PR contains breaking change. Pls follow [breaking change policy](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/43942/Policy-for-Breaking-Changes). "

- rule:
    type: checkbox
    keywords:
      - "WaitForARMFeedback"
    booleanFilterExpression: "!(ARMSignedOff||ARMChangesRequested||Approved-OkToMerge||WaitForARMRevisit)"
    onCheckedLabels:
      - WaitForARMFeedback
    onCheckedComments: "Hi, @${PRAuthor} your PR was labelled with WaitForARMFeedback. cc @${PRAssignee}"

- rule:
    type: checkbox
    keywords:
      - "I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow."
    onCheckedLabels:
      - ReadyForReview
    onCheckedComments: "Hi, @${PRAuthor} Thanks for your PR. I am workflow bot for review process. Here are some small tips. </br> <li> Please check the checkbox in first PR comments if applicable. </li> <li>If CI failed, Please fix CI error before PR merge. [How to fix?](https://aka.ms/ci-fix) </li> <li> PR assignee is responsible for your current PR reviewing and merging. </li> </br> Any feedback about review process or workflow bot, pls contact swagger and tools team. vsswagger@microsoft.com"

- rule:
    type: label
    label: BreakingChange
    onLabeledComments: "Hi, your PR meet breaking change."
# - rule:
#   type: approved
#   onApprovedLabel: approvedOkToMerge
#   onApprovedComments: "Hi, ${PRAuthor} your PR has been approved. what's need to do next..."

# - rule:
#   type: label
#   labelName: approve
#   onLabelComments: "hi, the PR labelled with xxx"
