---
- rule:
    type: checkbox
    keywords:
      - "Removing API(s)"
      - "Updating API in stable version"
    onCheckedLabels:
      - breakingChange
    onCheckedComments: "Hi, @${PRAuthor} your PR contains breaking change. Pls follow [breaking change policy](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/43942/Policy-for-Breaking-Changes). "

- rule:
    type: checkbox
    keywords:
      - "WaitForARMFeedback"
    booleanFilterExpression: "!(ARMSignedOff||ARMChangesRequested||Approved-OkToMerge||WaitForARMRevisit)"
    onCheckedLabels:
      - WaitForARMFeedback
    onCheckedComments: "Hi, @${PRAuthor} your PR was labelled with WaitForARMFeedback. cc @${PRAssignee}"

- rule:
    type: checkbox
    keywords:
      - "I have reviewed the [documentation](https://aka.ms/ameonboard) for the workflow."
    onCheckedLabels:
      - ReadyForReview
    onCheckedComments: "Hi, @${PRAuthor} Thanks for your PR."
# - rule:
#   type: approved
#   onApprovedLabel: approvedOkToMerge
#   onApprovedComments: "Hi, ${PRAuthor} your PR has been approved. what's need to do next..."

# - rule:
#   type: label
#   labelName: approve
#   onLabelComments: "hi, the PR labelled with xxx"
