---
- rule:
    label: Java
    booleanFilterExpression: "Java&&Mgnt"
    assignees:
      - ruowan
- rule:
    label: Python
    booleanFilterExpression: "Python&&Mgnt"
    assignees:
      - ruowan
      - NullMDR

- rule:
    booleanFilterExpression: "triage"
    label: Triage
    assignees:
      - ruowan
      - Dreamgoing
      - NullMDR
